---
- name:  Update n5 servers
  hosts: n5
  become: yes

  tasks: 
  - name: ensure default page removed
    file:
      path: /var/www/html/index.html
      state: absent

  - name: ensure site is updated
    git:
      repo: https://github.com/ravi2krishna/ecomm.git
      dest: /var/www/html 
...

