---
- name:  Update all servers
  hosts: all
  become: yes

  tasks:
  - name: ensure http is installed
    yum:
      name: httpd
      state: installed
    when: ansible_distribution == "Amazon"

  - name: ensure http is started
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Amazon"

  - name: ensure http is enabled
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "Amazon"
     
  - name: ensure apt is updated
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache is installed
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache is started
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache is enabled
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu"        
...

