---
- name:  Update n4 servers
  hosts: ub
  become: yes

  tasks: 
  - name: ensure apt is updated
    apt:
      update_cache: yes 

  - name: ensure apache is installed
    apt:
      name: apache2
      state: present

  - name: ensure apache is started
    service:
      name: apache2
      state: started

  - name: ensure apache is enabled
    service:
      name: apache2
      enabled: yes

...

